apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q19ql6vw3-python
  janus-idp.io/tekton: q19ql6vw3-python
  backstage.io/kubernetes-id: q19ql6vw3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q19ql6vw3-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
